// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module CLINT(
  input         clock,
                reset,
                auto_in_a_valid,
  input  [2:0]  auto_in_a_bits_opcode,
                auto_in_a_bits_param,
  input  [1:0]  auto_in_a_bits_size,
  input  [11:0] auto_in_a_bits_source,
  input  [25:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_a_bits_corrupt,
                auto_in_d_ready,
                io_rtcTick,
  output        auto_int_out_10_0,
                auto_int_out_10_1,
                auto_int_out_9_0,
                auto_int_out_9_1,
                auto_int_out_8_0,
                auto_int_out_8_1,
                auto_int_out_7_0,
                auto_int_out_7_1,
                auto_int_out_6_0,
                auto_int_out_6_1,
                auto_int_out_5_0,
                auto_int_out_5_1,
                auto_int_out_4_0,
                auto_int_out_4_1,
                auto_int_out_3_0,
                auto_int_out_3_1,
                auto_int_out_2_0,
                auto_int_out_2_1,
                auto_int_out_1_0,
                auto_int_out_1_1,
                auto_int_out_0_0,
                auto_int_out_0_1,
                auto_in_a_ready,
                auto_in_d_valid,
  output [2:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_size,
  output [11:0] auto_in_d_bits_source,
  output [63:0] auto_in_d_bits_data
);

  wire              out_woready_89;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_105;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_69;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_53;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_61;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_29;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_37;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_113;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_77;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_13;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_45;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_21;	// @[RegisterRouter.scala:83:24]
  reg  [63:0]       time_0;	// @[CLINT.scala:69:23]
  reg  [63:0]       timecmp_0;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_1;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_2;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_3;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_4;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_5;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_6;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_7;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_8;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_9;	// @[CLINT.scala:73:41]
  reg  [63:0]       timecmp_10;	// @[CLINT.scala:73:41]
  reg               ipi_0;	// @[CLINT.scala:74:41]
  reg               ipi_1;	// @[CLINT.scala:74:41]
  reg               ipi_2;	// @[CLINT.scala:74:41]
  reg               ipi_3;	// @[CLINT.scala:74:41]
  reg               ipi_4;	// @[CLINT.scala:74:41]
  reg               ipi_5;	// @[CLINT.scala:74:41]
  reg               ipi_6;	// @[CLINT.scala:74:41]
  reg               ipi_7;	// @[CLINT.scala:74:41]
  reg               ipi_8;	// @[CLINT.scala:74:41]
  reg               ipi_9;	// @[CLINT.scala:74:41]
  reg               ipi_10;	// @[CLINT.scala:74:41]
  wire              out_front_bits_read = auto_in_a_bits_opcode == 3'h4;	// @[RegisterRouter.scala:72:36]
  wire [7:0]        _GEN = {auto_in_a_bits_address[15], auto_in_a_bits_address[13:7]};	// @[RegisterRouter.scala:83:24]
  wire              _out_out_bits_data_WIRE_26 = _GEN == 8'h0;	// @[Bitwise.scala:77:12, RegisterRouter.scala:83:24]
  wire              valids_1_0 = out_woready_13 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_1 = out_woready_13 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_2 = out_woready_13 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_3 = out_woready_13 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_4 = out_woready_13 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_5 = out_woready_13 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_6 = out_woready_13 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1_7 = out_woready_13 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_0 = out_woready_21 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_1 = out_woready_21 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_2 = out_woready_21 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_3 = out_woready_21 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_4 = out_woready_21 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_5 = out_woready_21 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_6 = out_woready_21 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_11_7 = out_woready_21 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_0 = out_woready_29 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_1 = out_woready_29 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_2 = out_woready_29 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_3 = out_woready_29 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_4 = out_woready_29 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_5 = out_woready_29 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_6 = out_woready_29 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5_7 = out_woready_29 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_0 = out_woready_37 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_1 = out_woready_37 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_2 = out_woready_37 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_3 = out_woready_37 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_4 = out_woready_37 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_5 = out_woready_37 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_6 = out_woready_37 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4_7 = out_woready_37 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_0 = out_woready_45 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_1 = out_woready_45 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2 = out_woready_45 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3 = out_woready_45 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_4 = out_woready_45 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_5 = out_woready_45 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6 = out_woready_45 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7 = out_woready_45 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_0 = out_woready_53 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_1 = out_woready_53 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_2 = out_woready_53 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_3 = out_woready_53 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_4 = out_woready_53 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_5 = out_woready_53 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_6 = out_woready_53 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_7_7 = out_woready_53 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_0 = out_woready_61 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_1 = out_woready_61 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_2 = out_woready_61 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_3 = out_woready_61 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_4 = out_woready_61 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_5 = out_woready_61 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_6 = out_woready_61 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_6_7 = out_woready_61 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_0 = out_woready_69 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_1 = out_woready_69 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_2 = out_woready_69 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_3 = out_woready_69 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_4 = out_woready_69 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_5 = out_woready_69 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_6 = out_woready_69 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_8_7 = out_woready_69 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_0 = out_woready_77 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_1 = out_woready_77 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_2 = out_woready_77 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_3 = out_woready_77 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_4 = out_woready_77 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_5 = out_woready_77 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_6 = out_woready_77 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_2_7 = out_woready_77 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_0 = out_woready_89 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_1 = out_woready_89 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_2 = out_woready_89 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_3 = out_woready_89 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_4 = out_woready_89 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_5 = out_woready_89 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_6 = out_woready_89 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_10_7 = out_woready_89 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_0 = out_woready_105 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_1 = out_woready_105 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_2 = out_woready_105 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_3 = out_woready_105 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_4 = out_woready_105 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_5 = out_woready_105 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_6 = out_woready_105 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_9_7 = out_woready_105 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_0 = out_woready_113 & auto_in_a_bits_mask[0];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_1 = out_woready_113 & auto_in_a_bits_mask[1];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_2 = out_woready_113 & auto_in_a_bits_mask[2];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_3 = out_woready_113 & auto_in_a_bits_mask[3];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_4 = out_woready_113 & auto_in_a_bits_mask[4];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_5 = out_woready_113 & auto_in_a_bits_mask[5];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_6 = out_woready_113 & auto_in_a_bits_mask[6];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire              valids_3_7 = out_woready_113 & auto_in_a_bits_mask[7];	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
  wire [4:0]        out_oindex = {auto_in_a_bits_address[14], auto_in_a_bits_address[6:3]};	// @[Cat.scala:33:92, RegisterRouter.scala:83:24]
  wire [4:0]        _GEN_0 = {auto_in_a_bits_address[14], auto_in_a_bits_address[6:3]};	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              _out_wofireMux_T_2 = auto_in_a_valid & auto_in_d_ready & ~out_front_bits_read;	// @[RegisterRouter.scala:72:36, :83:24]
  wire              out_woready_2 = _out_wofireMux_T_2 & _GEN_0 == 5'h0 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_92 = _out_wofireMux_T_2 & _GEN_0 == 5'h1 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_96 = _out_wofireMux_T_2 & _GEN_0 == 5'h2 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_116 = _out_wofireMux_T_2 & _GEN_0 == 5'h3 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_80 = _out_wofireMux_T_2 & _GEN_0 == 5'h4 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_21 = _out_wofireMux_T_2 & _GEN_0 == 5'hF & (&_GEN);	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_45 = _out_wofireMux_T_2 & _GEN_0 == 5'h10 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_13 = _out_wofireMux_T_2 & _GEN_0 == 5'h11 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_77 = _out_wofireMux_T_2 & _GEN_0 == 5'h12 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_113 = _out_wofireMux_T_2 & _GEN_0 == 5'h13 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_37 = _out_wofireMux_T_2 & _GEN_0 == 5'h14 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_29 = _out_wofireMux_T_2 & _GEN_0 == 5'h15 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_61 = _out_wofireMux_T_2 & _GEN_0 == 5'h16 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_53 = _out_wofireMux_T_2 & _GEN_0 == 5'h17 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_69 = _out_wofireMux_T_2 & _GEN_0 == 5'h18 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_105 = _out_wofireMux_T_2 & _GEN_0 == 5'h19 & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_89 = _out_wofireMux_T_2 & _GEN_0 == 5'h1A & _out_out_bits_data_WIRE_26;	// @[OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire [31:0]       _GEN_1 = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {&_GEN}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}, {_out_out_bits_data_WIRE_26}};	// @[CLINT.scala:70:38, MuxLiteral.scala:49:10, RegisterRouter.scala:83:24]
  wire [31:0][63:0] _GEN_2 = {{64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {timecmp_10}, {timecmp_9}, {timecmp_8}, {timecmp_7}, {timecmp_6}, {timecmp_5}, {timecmp_4}, {timecmp_3}, {timecmp_2}, {timecmp_1}, {timecmp_0}, {time_0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {64'h0}, {{63'h0, ipi_10}}, {{31'h0, ipi_9, 31'h0, ipi_8}}, {{31'h0, ipi_7, 31'h0, ipi_6}}, {{31'h0, ipi_5, 31'h0, ipi_4}}, {{31'h0, ipi_3, 31'h0, ipi_2}}, {{31'h0, ipi_1, 31'h0, ipi_0}}};	// @[CLINT.scala:69:23, :73:41, :74:41, MuxLiteral.scala:49:{10,48}, RegisterRouter.scala:83:24]
  wire [2:0]        bundleIn_0_d_bits_opcode = {2'h0, out_front_bits_read};	// @[RegisterRouter.scala:72:36, :98:19]
  always @(posedge clock) begin
    if (reset) begin
      time_0 <= 64'h0;	// @[CLINT.scala:69:23]
      ipi_0 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_1 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_2 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_3 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_4 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_5 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_6 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_7 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_8 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_9 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
      ipi_10 <= 1'h0;	// @[CLINT.scala:73:41, :74:41]
    end
    else begin
      if (valids_11_0 | valids_11_1 | valids_11_2 | valids_11_3 | valids_11_4 | valids_11_5 | valids_11_6 | valids_11_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
        time_0 <= {valids_11_7 ? auto_in_a_bits_data[63:56] : time_0[63:56], valids_11_6 ? auto_in_a_bits_data[55:48] : time_0[55:48], valids_11_5 ? auto_in_a_bits_data[47:40] : time_0[47:40], valids_11_4 ? auto_in_a_bits_data[39:32] : time_0[39:32], valids_11_3 ? auto_in_a_bits_data[31:24] : time_0[31:24], valids_11_2 ? auto_in_a_bits_data[23:16] : time_0[23:16], valids_11_1 ? auto_in_a_bits_data[15:8] : time_0[15:8], valids_11_0 ? auto_in_a_bits_data[7:0] : time_0[7:0]};	// @[CLINT.scala:69:23, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
      else if (io_rtcTick)
        time_0 <= time_0 + 64'h1;	// @[CLINT.scala:69:23, :70:38]
      if (out_woready_2 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_0 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_2 & auto_in_a_bits_mask[4])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_1 <= auto_in_a_bits_data[32];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_92 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_2 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_92 & auto_in_a_bits_mask[4])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_3 <= auto_in_a_bits_data[32];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_96 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_4 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_96 & auto_in_a_bits_mask[4])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_5 <= auto_in_a_bits_data[32];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_116 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_6 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_116 & auto_in_a_bits_mask[4])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_7 <= auto_in_a_bits_data[32];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_80 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_8 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (out_woready_80 & auto_in_a_bits_mask[4])	// @[Bitwise.scala:28:17, RegisterRouter.scala:83:24]
        ipi_9 <= auto_in_a_bits_data[32];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
      if (_out_wofireMux_T_2 & _GEN_0 == 5'h5 & _out_out_bits_data_WIRE_26 & auto_in_a_bits_mask[0])	// @[Bitwise.scala:28:17, OneHot.scala:57:35, RegisterRouter.scala:83:24]
        ipi_10 <= auto_in_a_bits_data[0];	// @[CLINT.scala:74:41, RegisterRouter.scala:83:24]
    end
    if (valids_0 | valids_1 | valids_2 | valids_3 | valids_4 | valids_5 | valids_6 | valids_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_0 <= {valids_7 ? auto_in_a_bits_data[63:56] : timecmp_0[63:56], valids_6 ? auto_in_a_bits_data[55:48] : timecmp_0[55:48], valids_5 ? auto_in_a_bits_data[47:40] : timecmp_0[47:40], valids_4 ? auto_in_a_bits_data[39:32] : timecmp_0[39:32], valids_3 ? auto_in_a_bits_data[31:24] : timecmp_0[31:24], valids_2 ? auto_in_a_bits_data[23:16] : timecmp_0[23:16], valids_1 ? auto_in_a_bits_data[15:8] : timecmp_0[15:8], valids_0 ? auto_in_a_bits_data[7:0] : timecmp_0[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_1_0 | valids_1_1 | valids_1_2 | valids_1_3 | valids_1_4 | valids_1_5 | valids_1_6 | valids_1_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_1 <= {valids_1_7 ? auto_in_a_bits_data[63:56] : timecmp_1[63:56], valids_1_6 ? auto_in_a_bits_data[55:48] : timecmp_1[55:48], valids_1_5 ? auto_in_a_bits_data[47:40] : timecmp_1[47:40], valids_1_4 ? auto_in_a_bits_data[39:32] : timecmp_1[39:32], valids_1_3 ? auto_in_a_bits_data[31:24] : timecmp_1[31:24], valids_1_2 ? auto_in_a_bits_data[23:16] : timecmp_1[23:16], valids_1_1 ? auto_in_a_bits_data[15:8] : timecmp_1[15:8], valids_1_0 ? auto_in_a_bits_data[7:0] : timecmp_1[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_2_0 | valids_2_1 | valids_2_2 | valids_2_3 | valids_2_4 | valids_2_5 | valids_2_6 | valids_2_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_2 <= {valids_2_7 ? auto_in_a_bits_data[63:56] : timecmp_2[63:56], valids_2_6 ? auto_in_a_bits_data[55:48] : timecmp_2[55:48], valids_2_5 ? auto_in_a_bits_data[47:40] : timecmp_2[47:40], valids_2_4 ? auto_in_a_bits_data[39:32] : timecmp_2[39:32], valids_2_3 ? auto_in_a_bits_data[31:24] : timecmp_2[31:24], valids_2_2 ? auto_in_a_bits_data[23:16] : timecmp_2[23:16], valids_2_1 ? auto_in_a_bits_data[15:8] : timecmp_2[15:8], valids_2_0 ? auto_in_a_bits_data[7:0] : timecmp_2[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_3_0 | valids_3_1 | valids_3_2 | valids_3_3 | valids_3_4 | valids_3_5 | valids_3_6 | valids_3_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_3 <= {valids_3_7 ? auto_in_a_bits_data[63:56] : timecmp_3[63:56], valids_3_6 ? auto_in_a_bits_data[55:48] : timecmp_3[55:48], valids_3_5 ? auto_in_a_bits_data[47:40] : timecmp_3[47:40], valids_3_4 ? auto_in_a_bits_data[39:32] : timecmp_3[39:32], valids_3_3 ? auto_in_a_bits_data[31:24] : timecmp_3[31:24], valids_3_2 ? auto_in_a_bits_data[23:16] : timecmp_3[23:16], valids_3_1 ? auto_in_a_bits_data[15:8] : timecmp_3[15:8], valids_3_0 ? auto_in_a_bits_data[7:0] : timecmp_3[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_4_0 | valids_4_1 | valids_4_2 | valids_4_3 | valids_4_4 | valids_4_5 | valids_4_6 | valids_4_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_4 <= {valids_4_7 ? auto_in_a_bits_data[63:56] : timecmp_4[63:56], valids_4_6 ? auto_in_a_bits_data[55:48] : timecmp_4[55:48], valids_4_5 ? auto_in_a_bits_data[47:40] : timecmp_4[47:40], valids_4_4 ? auto_in_a_bits_data[39:32] : timecmp_4[39:32], valids_4_3 ? auto_in_a_bits_data[31:24] : timecmp_4[31:24], valids_4_2 ? auto_in_a_bits_data[23:16] : timecmp_4[23:16], valids_4_1 ? auto_in_a_bits_data[15:8] : timecmp_4[15:8], valids_4_0 ? auto_in_a_bits_data[7:0] : timecmp_4[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_5_0 | valids_5_1 | valids_5_2 | valids_5_3 | valids_5_4 | valids_5_5 | valids_5_6 | valids_5_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_5 <= {valids_5_7 ? auto_in_a_bits_data[63:56] : timecmp_5[63:56], valids_5_6 ? auto_in_a_bits_data[55:48] : timecmp_5[55:48], valids_5_5 ? auto_in_a_bits_data[47:40] : timecmp_5[47:40], valids_5_4 ? auto_in_a_bits_data[39:32] : timecmp_5[39:32], valids_5_3 ? auto_in_a_bits_data[31:24] : timecmp_5[31:24], valids_5_2 ? auto_in_a_bits_data[23:16] : timecmp_5[23:16], valids_5_1 ? auto_in_a_bits_data[15:8] : timecmp_5[15:8], valids_5_0 ? auto_in_a_bits_data[7:0] : timecmp_5[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_6_0 | valids_6_1 | valids_6_2 | valids_6_3 | valids_6_4 | valids_6_5 | valids_6_6 | valids_6_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_6 <= {valids_6_7 ? auto_in_a_bits_data[63:56] : timecmp_6[63:56], valids_6_6 ? auto_in_a_bits_data[55:48] : timecmp_6[55:48], valids_6_5 ? auto_in_a_bits_data[47:40] : timecmp_6[47:40], valids_6_4 ? auto_in_a_bits_data[39:32] : timecmp_6[39:32], valids_6_3 ? auto_in_a_bits_data[31:24] : timecmp_6[31:24], valids_6_2 ? auto_in_a_bits_data[23:16] : timecmp_6[23:16], valids_6_1 ? auto_in_a_bits_data[15:8] : timecmp_6[15:8], valids_6_0 ? auto_in_a_bits_data[7:0] : timecmp_6[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_7_0 | valids_7_1 | valids_7_2 | valids_7_3 | valids_7_4 | valids_7_5 | valids_7_6 | valids_7_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_7 <= {valids_7_7 ? auto_in_a_bits_data[63:56] : timecmp_7[63:56], valids_7_6 ? auto_in_a_bits_data[55:48] : timecmp_7[55:48], valids_7_5 ? auto_in_a_bits_data[47:40] : timecmp_7[47:40], valids_7_4 ? auto_in_a_bits_data[39:32] : timecmp_7[39:32], valids_7_3 ? auto_in_a_bits_data[31:24] : timecmp_7[31:24], valids_7_2 ? auto_in_a_bits_data[23:16] : timecmp_7[23:16], valids_7_1 ? auto_in_a_bits_data[15:8] : timecmp_7[15:8], valids_7_0 ? auto_in_a_bits_data[7:0] : timecmp_7[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_8_0 | valids_8_1 | valids_8_2 | valids_8_3 | valids_8_4 | valids_8_5 | valids_8_6 | valids_8_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_8 <= {valids_8_7 ? auto_in_a_bits_data[63:56] : timecmp_8[63:56], valids_8_6 ? auto_in_a_bits_data[55:48] : timecmp_8[55:48], valids_8_5 ? auto_in_a_bits_data[47:40] : timecmp_8[47:40], valids_8_4 ? auto_in_a_bits_data[39:32] : timecmp_8[39:32], valids_8_3 ? auto_in_a_bits_data[31:24] : timecmp_8[31:24], valids_8_2 ? auto_in_a_bits_data[23:16] : timecmp_8[23:16], valids_8_1 ? auto_in_a_bits_data[15:8] : timecmp_8[15:8], valids_8_0 ? auto_in_a_bits_data[7:0] : timecmp_8[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_9_0 | valids_9_1 | valids_9_2 | valids_9_3 | valids_9_4 | valids_9_5 | valids_9_6 | valids_9_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_9 <= {valids_9_7 ? auto_in_a_bits_data[63:56] : timecmp_9[63:56], valids_9_6 ? auto_in_a_bits_data[55:48] : timecmp_9[55:48], valids_9_5 ? auto_in_a_bits_data[47:40] : timecmp_9[47:40], valids_9_4 ? auto_in_a_bits_data[39:32] : timecmp_9[39:32], valids_9_3 ? auto_in_a_bits_data[31:24] : timecmp_9[31:24], valids_9_2 ? auto_in_a_bits_data[23:16] : timecmp_9[23:16], valids_9_1 ? auto_in_a_bits_data[15:8] : timecmp_9[15:8], valids_9_0 ? auto_in_a_bits_data[7:0] : timecmp_9[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
    if (valids_10_0 | valids_10_1 | valids_10_2 | valids_10_3 | valids_10_4 | valids_10_5 | valids_10_6 | valids_10_7)	// @[RegField.scala:154:27, RegisterRouter.scala:83:24]
      timecmp_10 <= {valids_10_7 ? auto_in_a_bits_data[63:56] : timecmp_10[63:56], valids_10_6 ? auto_in_a_bits_data[55:48] : timecmp_10[55:48], valids_10_5 ? auto_in_a_bits_data[47:40] : timecmp_10[47:40], valids_10_4 ? auto_in_a_bits_data[39:32] : timecmp_10[39:32], valids_10_3 ? auto_in_a_bits_data[31:24] : timecmp_10[31:24], valids_10_2 ? auto_in_a_bits_data[23:16] : timecmp_10[23:16], valids_10_1 ? auto_in_a_bits_data[15:8] : timecmp_10[15:8], valids_10_0 ? auto_in_a_bits_data[7:0] : timecmp_10[7:0]};	// @[CLINT.scala:73:41, RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, RegisterRouter.scala:83:24]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        time_0 = {_RANDOM_0, _RANDOM_1};	// @[CLINT.scala:69:23]
        timecmp_0 = {_RANDOM_2, _RANDOM_3};	// @[CLINT.scala:73:41]
        timecmp_1 = {_RANDOM_4, _RANDOM_5};	// @[CLINT.scala:73:41]
        timecmp_2 = {_RANDOM_6, _RANDOM_7};	// @[CLINT.scala:73:41]
        timecmp_3 = {_RANDOM_8, _RANDOM_9};	// @[CLINT.scala:73:41]
        timecmp_4 = {_RANDOM_10, _RANDOM_11};	// @[CLINT.scala:73:41]
        timecmp_5 = {_RANDOM_12, _RANDOM_13};	// @[CLINT.scala:73:41]
        timecmp_6 = {_RANDOM_14, _RANDOM_15};	// @[CLINT.scala:73:41]
        timecmp_7 = {_RANDOM_16, _RANDOM_17};	// @[CLINT.scala:73:41]
        timecmp_8 = {_RANDOM_18, _RANDOM_19};	// @[CLINT.scala:73:41]
        timecmp_9 = {_RANDOM_20, _RANDOM_21};	// @[CLINT.scala:73:41]
        timecmp_10 = {_RANDOM_22, _RANDOM_23};	// @[CLINT.scala:73:41]
        ipi_0 = _RANDOM_24[0];	// @[CLINT.scala:74:41]
        ipi_1 = _RANDOM_24[1];	// @[CLINT.scala:74:41]
        ipi_2 = _RANDOM_24[2];	// @[CLINT.scala:74:41]
        ipi_3 = _RANDOM_24[3];	// @[CLINT.scala:74:41]
        ipi_4 = _RANDOM_24[4];	// @[CLINT.scala:74:41]
        ipi_5 = _RANDOM_24[5];	// @[CLINT.scala:74:41]
        ipi_6 = _RANDOM_24[6];	// @[CLINT.scala:74:41]
        ipi_7 = _RANDOM_24[7];	// @[CLINT.scala:74:41]
        ipi_8 = _RANDOM_24[8];	// @[CLINT.scala:74:41]
        ipi_9 = _RANDOM_24[9];	// @[CLINT.scala:74:41]
        ipi_10 = _RANDOM_24[10];	// @[CLINT.scala:74:41]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  TLMonitor_95 monitor (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (auto_in_d_ready),
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (auto_in_a_valid),
    .io_in_d_bits_opcode  (bundleIn_0_d_bits_opcode),	// @[RegisterRouter.scala:98:19]
    .io_in_d_bits_size    (auto_in_a_bits_size),
    .io_in_d_bits_source  (auto_in_a_bits_source)
  );
  assign auto_int_out_10_0 = ipi_10;	// @[CLINT.scala:74:41]
  assign auto_int_out_10_1 = time_0 >= timecmp_10;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_9_0 = ipi_9;	// @[CLINT.scala:74:41]
  assign auto_int_out_9_1 = time_0 >= timecmp_9;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_8_0 = ipi_8;	// @[CLINT.scala:74:41]
  assign auto_int_out_8_1 = time_0 >= timecmp_8;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_7_0 = ipi_7;	// @[CLINT.scala:74:41]
  assign auto_int_out_7_1 = time_0 >= timecmp_7;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_6_0 = ipi_6;	// @[CLINT.scala:74:41]
  assign auto_int_out_6_1 = time_0 >= timecmp_6;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_5_0 = ipi_5;	// @[CLINT.scala:74:41]
  assign auto_int_out_5_1 = time_0 >= timecmp_5;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_4_0 = ipi_4;	// @[CLINT.scala:74:41]
  assign auto_int_out_4_1 = time_0 >= timecmp_4;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_3_0 = ipi_3;	// @[CLINT.scala:74:41]
  assign auto_int_out_3_1 = time_0 >= timecmp_3;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_2_0 = ipi_2;	// @[CLINT.scala:74:41]
  assign auto_int_out_2_1 = time_0 >= timecmp_2;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_1_0 = ipi_1;	// @[CLINT.scala:74:41]
  assign auto_int_out_1_1 = time_0 >= timecmp_1;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_int_out_0_0 = ipi_0;	// @[CLINT.scala:74:41]
  assign auto_int_out_0_1 = time_0 >= timecmp_0;	// @[CLINT.scala:69:23, :73:41, :79:43]
  assign auto_in_a_ready = auto_in_d_ready;
  assign auto_in_d_valid = auto_in_a_valid;
  assign auto_in_d_bits_opcode = bundleIn_0_d_bits_opcode;	// @[RegisterRouter.scala:98:19]
  assign auto_in_d_bits_size = auto_in_a_bits_size;
  assign auto_in_d_bits_source = auto_in_a_bits_source;
  assign auto_in_d_bits_data = _GEN_1[out_oindex] ? _GEN_2[out_oindex] : 64'h0;	// @[CLINT.scala:69:23, Cat.scala:33:92, MuxLiteral.scala:49:10, RegisterRouter.scala:83:24]
endmodule

